live_config_reload: true

dynamic_title: true

window:
  opacity: 0.8

  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 120
    lines: 45

  padding:
    x: 0
    y: 0

  dynamic_padding: true

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: buttonless
  dynamic_padding: true
  opacity: 0.9
  # opacity: 1.0
  padding:
    x: 5
    y: 5
  startup_mode: Windowed

scrolling:
  history: 10000

font:
  size: 22.0
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    # family: Cascadia Code
    # family: Operator Mono Light
    family: FiraCode Nerd Font
    style: Light

  bold:
    family: "FiraCode Nerd Font"
    style: Medium

  italic:
    family: "FiraCode Nerd Font"
    style: Italic

  bold_italic:
    family: "FiraCode Nerd Font"
    style: Medium Italic

  # Italic font face
  # italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: Operator Mono Light Italic

    # The `style` can be specified to pick a specific face.
    # style: Italic

  # Point size
  size: 18.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true


colors:
  primary:
    background: "0x191724"
    foreground: "0xe0def4"
  cursor:
    text: "0xe0def4"
    cursor: "0x524f67"
  vi_mode_cursor:
    text: "0xe0def4"
    cursor: "0x524f67"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: "0xe0def4"
    background: "0x403d52"
  normal:
    black: "0x26233a"
    red: "0xeb6f92"
    green: "0x31748f"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xebbcba"
    white: "0xe0def4"
  bright:
    black: "0x6e6a86"
    red: "0xeb6f92"
    green: "0x31748f"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xebbcba"
    white: "0xe0def4"
  hints:
    start:
      foreground: "#908caa"
      background: "#1f1d2e"
    end:
      foreground: "#6e6a86"
      background: "#1f1d2e"


# --- Iceberg ------------------------------------------------------------------
# colors:
#   primary:
#     background: '0x000000'
#     foreground: '0xdddddd'
#
#   normal:
#     black:   '0x161821'
#     red:     '0xe27878'
#     green:   '0xb4be82'
#     yellow:  '0xe2a478'
#     blue:    '0x84a0c6'
#     magenta: '0xa093c7'
#     cyan:    '0x89b8c2'
#     white:   '0xc6c8d1'
#
#   bright:
#     black:   '0x6b7089'
#     red:     '0xe98989'
#     green:   '0xc0ca8e'
#     yellow:  '0xe9b189'
#     blue:    '0x91acd1'
#     magenta: '0xada0d3'
#     cyan:    '0x95c4ce'
#     white:   '0xd2d4de'

# Nord Theme
# colors:
#   primary:
#     background: '0x212121'
#     foreground: '0xD8DEE9'
#   cursor:
#     text: '0x2E3440'
#     cursor: '0xD8DEE9'
#   normal:
#     black: '0x3B4252'
#     red: '0xBF616A'
#     green: '0xA3BE8C'
#     yellow: '0xEBCB8B'
#     blue: '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan: '0x88C0D0'
#     white: '0xE5E9F0'
#   bright:
#     black: '0x4C566A'
#     red: '0xBF616A'
#     green: '0xA3BE8C'
#     yellow: '0xEBCB8B'
#     blue: '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan: '0x8FBCBB'
#     white: '0xECEFF4'

bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

# Mouse bindings
#
# Available fields:
#   - mouse
#   - action
#   - mods (optional)
#
# Values for `mouse`:
#   - Middle
#   - Left
#   - Right
#   - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  hide_when_typing: true

  #url:
  #  # URL launcher
  #  #
  #  # This program is executed when clicking on a text which is recognized as a URL.
  #  # The URL is always added to the command as the last parameter.
  #  #
  #  # When set to `None`, URL launching will be disabled completely.
  #  #
  #  # Default:
  #  #   - (macOS) open
  #  #   - (Linux) xdg-open
  #  #   - (Windows) explorer
  #  #launcher:
  #  #  program: xdg-open
  #  #  args: []

  #  # URL modifiers
  #  #
  #  # These are the modifiers that need to be held down for opening URLs when clicking
  #  # on them. The available modifiers are documented in the key binding section.
  #  modifiers: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

cursor:
  style: Block
  unfocused_hollow: true

# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true

key_bindings:
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus,  mods: Command, action: DecreaseFontSize }
  - { key: Key0,   mods: Command, action: ResetFontSize    }
  - { key: C,      mods: Command, action: Copy             }
  - { key: F,      mods: Command, action: ToggleFullscreen }
  - { key: N,      mods: Command, action: SpawnNewInstance }
  - { key: Q,      mods: Command, action: Quit             }
  - { key: V,      mods: Command, action: Paste            }
  - { key: W,      mods: Command, action: Quit             }

  # (macOS only)
  #- { key: Key0,   mods: Command,         action: ResetFontSize    }
  #- { key: Equals, mods: Command,         action: IncreaseFontSize }
  #- { key: Add,    mods: Command,         action: IncreaseFontSize }
  #- { key: Minus,  mods: Command,         action: DecreaseFontSize }
  #- { key: K,      mods: Command,         action: ClearHistory     }
  #- { key: K,      mods: Command,         chars: "\x0c"            }
  #- { key: V,      mods: Command,         action: Paste            }
  #- { key: C,      mods: Command,         action: Copy             }
  #- { key: H,      mods: Command,         action: Hide             }
  #- { key: Q,      mods: Command,         action: Quit             }
  #- { key: W,      mods: Command,         action: Quit             }

  - { key: F,        mods: Command|Control, action: ToggleFullscreen }
  - { key: Paste,                   action: Paste                            }
  - { key: Copy,                    action: Copy                             }
  - { key: L,        mods: Control, action: ClearLogNotice                   }
  - { key: L,        mods: Control, chars: "\x0c"                            }
  - { key: Home,     mods: Alt,     chars: "\x1b[1;3H"                       }
  - { key: Home,                    chars: "\x1bOH",        mode: AppCursor  }
  - { key: Home,                    chars: "\x1b[H",        mode: ~AppCursor }
  - { key: End,      mods: Alt,     chars: "\x1b[1;3F"                       }
  - { key: End,                     chars: "\x1bOF",        mode: AppCursor  }
  - { key: End,                     chars: "\x1b[F",        mode: ~AppCursor }
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~",     mode: Alt        }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                       }
  - { key: PageUp,   mods: Alt,     chars: "\x1b[5;3~"                       }
  - { key: PageUp,                  chars: "\x1b[5~"                         }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~",     mode: Alt        }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                       }
  - { key: PageDown, mods: Alt,     chars: "\x1b[6;3~"                       }
  - { key: PageDown,                chars: "\x1b[6~"                         }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                          }
  - { key: Back,                    chars: "\x7f"                            }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                        }
  - { key: Insert,                  chars: "\x1b[2~"                         }
  - { key: Delete,                  chars: "\x1b[3~"                         }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                       }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                       }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                       }
  - { key: Left,                    chars: "\x1b[D",        mode: ~AppCursor }
  - { key: Left,                    chars: "\x1bOD",        mode: AppCursor  }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                       }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                       }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                       }
  - { key: Right,                   chars: "\x1b[C",        mode: ~AppCursor }
  - { key: Right,                   chars: "\x1bOC",        mode: AppCursor  }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                       }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                       }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                       }
  - { key: Up,                      chars: "\x1b[A",        mode: ~AppCursor }
  - { key: Up,                      chars: "\x1bOA",        mode: AppCursor  }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                       }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                       }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                       }
  - { key: Down,                    chars: "\x1b[B",        mode: ~AppCursor }
  - { key: Down,                    chars: "\x1bOB",        mode: AppCursor  }
  - { key: F1,                      chars: "\x1bOP"                          }
  - { key: F2,                      chars: "\x1bOQ"                          }
  - { key: F3,                      chars: "\x1bOR"                          }
  - { key: F4,                      chars: "\x1bOS"                          }
  - { key: F5,                      chars: "\x1b[15~"                        }
  - { key: F6,                      chars: "\x1b[17~"                        }
  - { key: F7,                      chars: "\x1b[18~"                        }
  - { key: F8,                      chars: "\x1b[19~"                        }
  - { key: F9,                      chars: "\x1b[20~"                        }
  - { key: F10,                     chars: "\x1b[21~"                        }
  - { key: F11,                     chars: "\x1b[23~"                        }
  - { key: F12,                     chars: "\x1b[24~"                        }
  - { key: F1,       mods: Shift,   chars: "\x1b[1;2P"                       }
  - { key: F2,       mods: Shift,   chars: "\x1b[1;2Q"                       }
  - { key: F3,       mods: Shift,   chars: "\x1b[1;2R"                       }
  - { key: F4,       mods: Shift,   chars: "\x1b[1;2S"                       }
  - { key: F5,       mods: Shift,   chars: "\x1b[15;2~"                      }
  - { key: F6,       mods: Shift,   chars: "\x1b[17;2~"                      }
  - { key: F7,       mods: Shift,   chars: "\x1b[18;2~"                      }
  - { key: F8,       mods: Shift,   chars: "\x1b[19;2~"                      }
  - { key: F9,       mods: Shift,   chars: "\x1b[20;2~"                      }
  - { key: F10,      mods: Shift,   chars: "\x1b[21;2~"                      }
  - { key: F11,      mods: Shift,   chars: "\x1b[23;2~"                      }
  - { key: F12,      mods: Shift,   chars: "\x1b[24;2~"                      }
  - { key: F1,       mods: Control, chars: "\x1b[1;5P"                       }
  - { key: F2,       mods: Control, chars: "\x1b[1;5Q"                       }
  - { key: F3,       mods: Control, chars: "\x1b[1;5R"                       }
  - { key: F4,       mods: Control, chars: "\x1b[1;5S"                       }
  - { key: F5,       mods: Control, chars: "\x1b[15;5~"                      }
  - { key: F6,       mods: Control, chars: "\x1b[17;5~"                      }
  - { key: F7,       mods: Control, chars: "\x1b[18;5~"                      }
  - { key: F8,       mods: Control, chars: "\x1b[19;5~"                      }
  - { key: F9,       mods: Control, chars: "\x1b[20;5~"                      }
  - { key: F10,      mods: Control, chars: "\x1b[21;5~"                      }
  - { key: F11,      mods: Control, chars: "\x1b[23;5~"                      }
  - { key: F12,      mods: Control, chars: "\x1b[24;5~"                      }
  - { key: F1,       mods: Alt,     chars: "\x1b[1;6P"                       }
  - { key: F2,       mods: Alt,     chars: "\x1b[1;6Q"                       }
  - { key: F3,       mods: Alt,     chars: "\x1b[1;6R"                       }
  - { key: F4,       mods: Alt,     chars: "\x1b[1;6S"                       }
  - { key: F5,       mods: Alt,     chars: "\x1b[15;6~"                      }
  - { key: F6,       mods: Alt,     chars: "\x1b[17;6~"                      }
  - { key: F7,       mods: Alt,     chars: "\x1b[18;6~"                      }
  - { key: F8,       mods: Alt,     chars: "\x1b[19;6~"                      }
  - { key: F9,       mods: Alt,     chars: "\x1b[20;6~"                      }
  - { key: F10,      mods: Alt,     chars: "\x1b[21;6~"                      }
  - { key: F11,      mods: Alt,     chars: "\x1b[23;6~"                      }
  - { key: F12,      mods: Alt,     chars: "\x1b[24;6~"                      }
  - { key: F1,       mods: Super,   chars: "\x1b[1;3P"                       }
  - { key: F2,       mods: Super,   chars: "\x1b[1;3Q"                       }
  - { key: F3,       mods: Super,   chars: "\x1b[1;3R"                       }
  - { key: F4,       mods: Super,   chars: "\x1b[1;3S"                       }
  - { key: F5,       mods: Super,   chars: "\x1b[15;3~"                      }
  - { key: F6,       mods: Super,   chars: "\x1b[17;3~"                      }
  - { key: F7,       mods: Super,   chars: "\x1b[18;3~"                      }
  - { key: F8,       mods: Super,   chars: "\x1b[19;3~"                      }
  - { key: F9,       mods: Super,   chars: "\x1b[20;3~"                      }
  - { key: F10,      mods: Super,   chars: "\x1b[21;3~"                      }
  - { key: F11,      mods: Super,   chars: "\x1b[23;3~"                      }
  - { key: F12,      mods: Super,   chars: "\x1b[24;3~"                      }
  - { key: NumpadEnter,             chars: "\n"                              }
