live_config_reload: true

dynamic_title: true

window:
  decorations: buttonless
  dynamic_padding: true
  opacity: 0.9
  # opacity: 1.0
  padding:
    x: 5
    y: 5
  startup_mode: Windowed

scrolling:
  history: 10000

font:
  size: 22.0
  normal:
    family: "FiraCode Nerd Font"
    # family: "Input Mono Narrow"
    # family: "DaddyTimeMono Nerd Font" # no "style"
    # family: "Monofur Nerd Font"
    # family: "MesloLGS Nerd Font"
    # family: "Input"
    # family: "VictorMono Nerd Font"
    # family: "Hack Nerd Font"
    style: Light

  bold:
    family: "FiraCode Nerd Font"
    style: Medium

  italic:
    family: "FiraCode Nerd Font"
    style: Italic

  bold_italic:
    family: "FiraCode Nerd Font"
    style: Medium Italic

  offset:
    x: 1
    y: 2

draw_bold_text_with_bright_colors: true


colors:
  primary:
    background: "0x191724"
    foreground: "0xe0def4"
  cursor:
    text: "0xe0def4"
    cursor: "0x524f67"
  vi_mode_cursor:
    text: "0xe0def4"
    cursor: "0x524f67"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: "0xe0def4"
    background: "0x403d52"
  normal:
    black: "0x26233a"
    red: "0xeb6f92"
    green: "0x31748f"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xebbcba"
    white: "0xe0def4"
  bright:
    black: "0x6e6a86"
    red: "0xeb6f92"
    green: "0x31748f"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xebbcba"
    white: "0xe0def4"
  hints:
    start:
      foreground: "#908caa"
      background: "#1f1d2e"
    end:
      foreground: "#6e6a86"
      background: "#1f1d2e"


# --- Iceberg ------------------------------------------------------------------
# colors:
#   primary:
#     background: '0x000000'
#     foreground: '0xdddddd'
#
#   normal:
#     black:   '0x161821'
#     red:     '0xe27878'
#     green:   '0xb4be82'
#     yellow:  '0xe2a478'
#     blue:    '0x84a0c6'
#     magenta: '0xa093c7'
#     cyan:    '0x89b8c2'
#     white:   '0xc6c8d1'
#
#   bright:
#     black:   '0x6b7089'
#     red:     '0xe98989'
#     green:   '0xc0ca8e'
#     yellow:  '0xe9b189'
#     blue:    '0x91acd1'
#     magenta: '0xada0d3'
#     cyan:    '0x95c4ce'
#     white:   '0xd2d4de'

# Nord Theme
# colors:
#   primary:
#     background: '0x212121'
#     foreground: '0xD8DEE9'
#   cursor:
#     text: '0x2E3440'
#     cursor: '0xD8DEE9'
#   normal:
#     black: '0x3B4252'
#     red: '0xBF616A'
#     green: '0xA3BE8C'
#     yellow: '0xEBCB8B'
#     blue: '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan: '0x88C0D0'
#     white: '0xE5E9F0'
#   bright:
#     black: '0x4C566A'
#     red: '0xBF616A'
#     green: '0xA3BE8C'
#     yellow: '0xEBCB8B'
#     blue: '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan: '0x8FBCBB'
#     white: '0xECEFF4'

bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

cursor:
  style: Block
  unfocused_hollow: true

# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true

key_bindings:
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus,  mods: Command, action: DecreaseFontSize }
  - { key: Key0,   mods: Command, action: ResetFontSize    }
  - { key: C,      mods: Command, action: Copy             }
  - { key: F,      mods: Command, action: ToggleFullscreen }
  - { key: N,      mods: Command, action: SpawnNewInstance }
  - { key: Q,      mods: Command, action: Quit             }
  - { key: V,      mods: Command, action: Paste            }
  - { key: W,      mods: Command, action: Quit             }

