name: sh
root: ~/code/sohohouse

windows:
  - notes:
    - cd ~/Dropbox/Notes/Sohohouse
    - clear
    - nvim ./log.md
  - sohohouse:
    - cd ~/code/sohohouse
    - clear
  - term:
    - cd ~
    - clear
