scan_timeout = 10

prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "time",
    "directory",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "python",
    "ruby",
    "rust",
    "git_branch",
    "git_state",
    "git_status",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "jobs",
    "battery",
    "line_break",
    "character",
]

[time]
disabled = true
format = "[%H:%M]"
style = "blue"

[directory]
style = "bold blue"
truncation_length = 2
truncate_to_repo = true

[package]
style = "red"

[python]
style = "green"

[ruby]
style = "red"

[rust]
style = "red"

[git_branch]
style = "purple"
symbol = "🌱 "

[git_status]
style = "red"

[cmd_duration]
style = "yellow"
