
# tap repositories and their packages

tap homebrew/core
brew adns
brew autoconf
brew automake
brew bash
brew bat
brew bison
brew cabal-install
brew cairo
brew chruby
brew cmake
brew ctags
brew curl
brew diff-so-fancy
brew elixir
brew erlang
brew exa
brew exercism
brew fd
brew fontconfig
brew freetype
brew fribidi
brew fzf
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghc
brew git
brew glib
brew global --with-pygments --with-ctags
brew gmp
brew gnu-sed
brew gnupg
brew gnutls
brew go
brew gobject-introspection
brew gradle
brew graphite2
brew graphviz
brew harfbuzz
brew htop
brew httpie
brew hub
brew icu4c
brew imagemagick
brew imagemagick@6
brew jemalloc
brew jpeg
brew jq
brew json-c
brew libassuan
brew libcroco
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libpng
brew librsvg
brew libstfl
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvterm
brew libxml2
brew libxslt
brew libyaml
brew links
brew luajit
brew mas
brew msgpack
brew mysql@5.7
brew neovim
brew nettle
brew newsboat
brew node
brew npth
brew nvm
brew oniguruma
brew openssl
brew openssl@1.1
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew pinentry
brew pixman
brew pkg-config
brew plantuml
brew postgresql
brew python
brew python@2
brew rbspy
brew readline
brew reattach-to-user-namespace
brew redis
brew ripgrep
brew rtv
brew ruby
brew ruby-build
brew ruby-install
brew sl
brew sphinx-doc
brew sqlite
brew tailor
brew tealdeer
brew texinfo
brew the_silver_searcher
brew tmux
brew tree
brew unibilium
brew unixodbc
brew webp
brew wget
brew wxmac
brew xz
brew zsh
brew zsh-completions
brew zsh-syntax-highlighting

tap homebrew/versions

tap homebrew/cask
cask anki
cask typora

tap d12frosted/emacs-plus
brew emacs-plus

tap joshuaclayton/formulae
brew unused

tap neovim/neovim

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ghc@8.0
brew pdftk
brew qt@5.5

# Other Cask applications
cask daisydisk

# App Store applications
appstore 627545560 Alinof TimerPro (3.2.1)
appstore 1013897218 App Cleaner & Uninstaller (5.4)
appstore 847496013 Deckset (1.8.5)
appstore 406056744 Evernote (7.5)
appstore 1114591412 Memory Clean 2 (1.8)
appstore 929507092 PhotoScapeX (2.8.2)
appstore 588726889 ReadKit (2.5.4)
appstore 425955336 Skitch (2.8.2)
appstore 431364704 WhiteNoiseFree (7.3.1)
appstore 965079797 WorkDone - for Workflowy (2.0.2)
appstore 497799835 Xcode (10.0)
